-- Create countries table
CREATE TABLE IF NOT EXISTS countries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  iso_code VARCHAR(2) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  date_format VARCHAR(20) NOT NULL DEFAULT 'DD/MM/YYYY',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for better performance
CREATE INDEX IF NOT EXISTS idx_countries_iso_code ON countries(iso_code);
CREATE INDEX IF NOT EXISTS idx_countries_is_active ON countries(is_active);

-- Insert initial data for supported countries
INSERT INTO countries (iso_code, name, currency_code, date_format, is_active) VALUES
('BR', 'Brasil', 'BRL', 'DD/MM/YYYY', true),
('US', 'Estados Unidos', 'USD', 'MM/DD/YYYY', true),
('CA', 'Canadá', 'CAD', 'MM/DD/YYYY', true),
('MX', 'México', 'MXN', 'DD/MM/YYYY', true),
('AR', 'Argentina', 'ARS', 'DD/MM/YYYY', true),
('CL', 'Chile', 'CLP', 'DD/MM/YYYY', true),
('CO', 'Colômbia', 'COP', 'DD/MM/YYYY', true),
('PE', 'Peru', 'PEN', 'DD/MM/YYYY', true),
('UY', 'Uruguai', 'UYU', 'DD/MM/YYYY', true),
('PY', 'Paraguai', 'PYG', 'DD/MM/YYYY', true),
('BO', 'Bolívia', 'BOB', 'DD/MM/YYYY', true),
('EC', 'Equador', 'USD', 'DD/MM/YYYY', true),
('VE', 'Venezuela', 'VES', 'DD/MM/YYYY', true),
('GY', 'Guiana', 'GYD', 'DD/MM/YYYY', true),
('SR', 'Suriname', 'SRD', 'DD/MM/YYYY', true),
('GF', 'Guiana Francesa', 'EUR', 'DD/MM/YYYY', true),
('ES', 'Espanha', 'EUR', 'DD/MM/YYYY', true),
('PT', 'Portugal', 'EUR', 'DD/MM/YYYY', true),
('FR', 'França', 'EUR', 'DD/MM/YYYY', true),
('DE', 'Alemanha', 'EUR', 'DD/MM/YYYY', true),
('IT', 'Itália', 'EUR', 'DD/MM/YYYY', true),
('GB', 'Reino Unido', 'GBP', 'DD/MM/YYYY', true),
('IE', 'Irlanda', 'EUR', 'DD/MM/YYYY', true),
('NL', 'Holanda', 'EUR', 'DD/MM/YYYY', true),
('BE', 'Bélgica', 'EUR', 'DD/MM/YYYY', true),
('CH', 'Suíça', 'CHF', 'DD/MM/YYYY', true),
('AT', 'Áustria', 'EUR', 'DD/MM/YYYY', true),
('SE', 'Suécia', 'SEK', 'YYYY-MM-DD', true),
('NO', 'Noruega', 'NOK', 'DD/MM/YYYY', true),
('DK', 'Dinamarca', 'DKK', 'DD/MM/YYYY', true),
('FI', 'Finlândia', 'EUR', 'DD/MM/YYYY', true),
('PL', 'Polônia', 'PLN', 'DD/MM/YYYY', true),
('CZ', 'República Tcheca', 'CZK', 'DD/MM/YYYY', true),
('HU', 'Hungria', 'HUF', 'YYYY-MM-DD', true),
('RO', 'Romênia', 'RON', 'DD/MM/YYYY', true),
('BG', 'Bulgária', 'BGN', 'DD/MM/YYYY', true),
('HR', 'Croácia', 'EUR', 'DD/MM/YYYY', true),
('SI', 'Eslovênia', 'EUR', 'DD/MM/YYYY', true),
('SK', 'Eslováquia', 'EUR', 'DD/MM/YYYY', true),
('LT', 'Lituânia', 'EUR', 'YYYY-MM-DD', true),
('LV', 'Letônia', 'EUR', 'YYYY-MM-DD', true),
('EE', 'Estônia', 'EUR', 'DD/MM/YYYY', true),
('GR', 'Grécia', 'EUR', 'DD/MM/YYYY', true),
('CY', 'Chipre', 'EUR', 'DD/MM/YYYY', true),
('MT', 'Malta', 'EUR', 'DD/MM/YYYY', true),
('LU', 'Luxemburgo', 'EUR', 'DD/MM/YYYY', true),
('JP', 'Japão', 'JPY', 'YYYY/MM/DD', true),
('KR', 'Coreia do Sul', 'KRW', 'YYYY-MM-DD', true),
('CN', 'China', 'CNY', 'YYYY-MM-DD', true),
('IN', 'Índia', 'INR', 'DD/MM/YYYY', true),
('AU', 'Austrália', 'AUD', 'DD/MM/YYYY', true),
('NZ', 'Nova Zelândia', 'NZD', 'DD/MM/YYYY', true),
('ZA', 'África do Sul', 'ZAR', 'YYYY/MM/DD', true),
('EG', 'Egito', 'EGP', 'DD/MM/YYYY', true),
('NG', 'Nigéria', 'NGN', 'DD/MM/YYYY', true),
('KE', 'Quênia', 'KES', 'DD/MM/YYYY', true),
('MA', 'Marrocos', 'MAD', 'DD/MM/YYYY', true),
('TN', 'Tunísia', 'TND', 'DD/MM/YYYY', true),
('DZ', 'Argélia', 'DZD', 'DD/MM/YYYY', true),
('LY', 'Líbia', 'LYD', 'DD/MM/YYYY', true),
('SD', 'Sudão', 'SDG', 'DD/MM/YYYY', true),
('ET', 'Etiópia', 'ETB', 'DD/MM/YYYY', true),
('GH', 'Gana', 'GHS', 'DD/MM/YYYY', true),
('CI', 'Costa do Marfim', 'XOF', 'DD/MM/YYYY', true),
('SN', 'Senegal', 'XOF', 'DD/MM/YYYY', true),
('ML', 'Mali', 'XOF', 'DD/MM/YYYY', true),
('BF', 'Burkina Faso', 'XOF', 'DD/MM/YYYY', true),
('NE', 'Níger', 'XOF', 'DD/MM/YYYY', true),
('TD', 'Chade', 'XAF', 'DD/MM/YYYY', true),
('CM', 'Camarões', 'XAF', 'DD/MM/YYYY', true),
('CF', 'República Centro-Africana', 'XAF', 'DD/MM/YYYY', true),
('GA', 'Gabão', 'XAF', 'DD/MM/YYYY', true),
('CG', 'Congo', 'XAF', 'DD/MM/YYYY', true),
('CD', 'República Democrática do Congo', 'CDF', 'DD/MM/YYYY', true),
('AO', 'Angola', 'AOA', 'DD/MM/YYYY', true),
('ZM', 'Zâmbia', 'ZMW', 'DD/MM/YYYY', true),
('ZW', 'Zimbábue', 'ZWL', 'DD/MM/YYYY', true),
('BW', 'Botsuana', 'BWP', 'DD/MM/YYYY', true),
('NA', 'Namíbia', 'NAD', 'DD/MM/YYYY', true),
('SZ', 'Suazilândia', 'SZL', 'DD/MM/YYYY', true),
('LS', 'Lesoto', 'LSL', 'DD/MM/YYYY', true),
('MG', 'Madagascar', 'MGA', 'DD/MM/YYYY', true),
('MU', 'Maurício', 'MUR', 'DD/MM/YYYY', true),
('SC', 'Seicheles', 'SCR', 'DD/MM/YYYY', true),
('KM', 'Comores', 'KMF', 'DD/MM/YYYY', true),
('DJ', 'Djibuti', 'DJF', 'DD/MM/YYYY', true),
('SO', 'Somália', 'SOS', 'DD/MM/YYYY', true),
('ER', 'Eritreia', 'ERN', 'DD/MM/YYYY', true),
('UG', 'Uganda', 'UGX', 'DD/MM/YYYY', true),
('RW', 'Ruanda', 'RWF', 'DD/MM/YYYY', true),
('BI', 'Burundi', 'BIF', 'DD/MM/YYYY', true),
('TZ', 'Tanzânia', 'TZS', 'DD/MM/YYYY', true),
('MW', 'Malawi', 'MWK', 'DD/MM/YYYY', true),
('MZ', 'Moçambique', 'MZN', 'DD/MM/YYYY', true),
('ZM', 'Zâmbia', 'ZMW', 'DD/MM/YYYY', true),
('ZW', 'Zimbábue', 'ZWL', 'DD/MM/YYYY', true),
('BW', 'Botsuana', 'BWP', 'DD/MM/YYYY', true),
('NA', 'Namíbia', 'NAD', 'DD/MM/YYYY', true),
('SZ', 'Suazilândia', 'SZL', 'DD/MM/YYYY', true),
('LS', 'Lesoto', 'LSL', 'DD/MM/YYYY', true),
('MG', 'Madagascar', 'MGA', 'DD/MM/YYYY', true),
('MU', 'Maurício', 'MUR', 'DD/MM/YYYY', true),
('SC', 'Seicheles', 'SCR', 'DD/MM/YYYY', true),
('KM', 'Comores', 'KMF', 'DD/MM/YYYY', true),
('DJ', 'Djibuti', 'DJF', 'DD/MM/YYYY', true),
('SO', 'Somália', 'SOS', 'DD/MM/YYYY', true),
('ER', 'Eritreia', 'ERN', 'DD/MM/YYYY', true),
('UG', 'Uganda', 'UGX', 'DD/MM/YYYY', true),
('RW', 'Ruanda', 'RWF', 'DD/MM/YYYY', true),
('BI', 'Burundi', 'BIF', 'DD/MM/YYYY', true),
('TZ', 'Tanzânia', 'TZS', 'DD/MM/YYYY', true),
('MW', 'Malawi', 'MWK', 'DD/MM/YYYY', true),
('MZ', 'Moçambique', 'MZN', 'DD/MM/YYYY', true)
ON CONFLICT (iso_code) DO UPDATE SET
  name = EXCLUDED.name,
  currency_code = EXCLUDED.currency_code,
  date_format = EXCLUDED.date_format,
  is_active = EXCLUDED.is_active;

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_countries_updated_at 
    BEFORE UPDATE ON countries 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();
